# Generated by Django 3.1 on 2020-08-22 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mod_lua', '0002_auto_20200822_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Переменная')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_lua.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Переменная пользователя',
                'verbose_name_plural': 'Переменные пользователя',
            },
        ),
        migrations.CreateModel(
            name='ContextAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prio', models.IntegerField(verbose_name='Приоритет')),
                ('condition_field', models.CharField(default='destination_number', max_length=255, verbose_name='Поле условия')),
                ('condition_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение условия')),
                ('action', models.CharField(max_length=255, verbose_name='Действие')),
                ('action_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Данные')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_lua.context', verbose_name='Контекст')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
                'unique_together': {('context', 'prio')},
            },
        ),
    ]
