# Generated by Django 3.1 on 2020-08-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod_lua', '0003_contextaction_uservar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='context',
        ),
    ]
