# Generated by Django 3.1 on 2020-08-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_lua', '0005_auto_20200823_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivr',
            name='exit_sound',
            field=models.CharField(default='voicemail/vm-goodbye.wav', max_length=100, verbose_name='Выход'),
        ),
        migrations.AlterField(
            model_name='ivr',
            name='greet_long',
            field=models.CharField(default='ivr-welcome_to_freeswitch.wav', max_length=100, verbose_name='Приветствие'),
        ),
        migrations.AlterField(
            model_name='ivr',
            name='greet_short',
            field=models.CharField(default='ivr-welcome_to_freeswitch.wav', max_length=100, verbose_name='Приветствие кор.'),
        ),
        migrations.AlterField(
            model_name='ivr',
            name='invalid_sound',
            field=models.CharField(default='ivr/ivr-that_was_an_invalid_entry.wav', max_length=100, verbose_name='Ошибка ввода'),
        ),
    ]
