# Generated by Django 3.1.1 on 2020-09-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_lua', '0006_auto_20200823_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivr',
            name='greet_long',
            field=models.CharField(default='ivr/ivr-welcome_to_freeswitch.wav', max_length=100, verbose_name='Приветствие'),
        ),
        migrations.AlterField(
            model_name='ivr',
            name='greet_short',
            field=models.CharField(default='ivr/ivr-welcome_to_freeswitch.wav', max_length=100, verbose_name='Приветствие кор.'),
        ),
    ]
