# Generated by Django 3.1.1 on 2020-09-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_lua', '0007_auto_20200905_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100, verbose_name='UUID звонка')),
                ('src', models.CharField(max_length=100, verbose_name='А-номер')),
                ('dst', models.CharField(max_length=100, verbose_name='Б-номер')),
                ('direction', models.CharField(max_length=100, verbose_name='Направление')),
                ('time', models.DateTimeField(auto_now_add=True, max_length=100, verbose_name='Время звонка')),
                ('status', models.CharField(default='NOANSWER', max_length=100, verbose_name='Статус')),
                ('duration', models.IntegerField(default=0, verbose_name='Длительность')),
            ],
            options={
                'verbose_name': 'Звонок',
                'verbose_name_plural': 'Звонки',
            },
        ),
    ]
